name: Uptime Monitor

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site
      id: hello
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://clf-cleafy4-stg.cleafy.cloud/v1/status"
        expected-statuses: "200"
